server:
  tomcat:
    uri-encoding: UTF-8
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://volcano01.cc.com:3306/MovieRecommendSystem?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    tomcat:
      test-on-borrow: true
      test-while-idle: true
  mvc:
    view:
      prefix: /templates
      suffix: .html
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.good.moviemanager.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql